### ISSUE TITLE
Compatibility with Python 3.7 to 3.9

### ISSUE THREAD

**Issue by mancellin** [rte-france/pallas-thermohl#4]
FYI, despite Thermohl being listed as supporting Python 3.7 and above, it currently cannot be installed on Python <=3.9 because of Pyntb
```
ERROR: Ignored the following versions that require a different python version: 2023.0.0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement pyntb>=2023.0.0 (from thermohl) (from versions: none)
ERROR: No matching distribution found for pyntb>=2023.0.0
```

This has been fixed in https://github.com/eurobios-mews-labs/pyntb/pull/7, but Thermohl is looking for Pyntb on PyPI where this PR has not been pushed yet. But I don't know if it worth doing a PyPI release of Pyntb just for that.

**Comment by ecieren** [comment]
Pyntb 2024.0.1 has just been released; fix coming soon
